database:
  name: lostfound
  host: "127.0.0.1"
  port: 3306
  user: root
  pass: "请填写你本地数据库的密码"

jwt:
  key: "你的密钥字符串"
  issuer: "lost-and-found-backend"

register:
  admin_invite_code: "请填写你的邀请码"

upload:
  base_url: "http://localhost:8080" # 请根据实际环境修改